apiVersion: v1
kind: PersistentVolume # 指的是 k8s 有哪些 volume
metadata:
    name: my-local-pv
#    labels:
#        type: local
spec:
    storageClassName: manual # 要与 pvc 中的一致，不然它找不到所需的存储
    capacity:
        storage: 1Gi
    accessModes:
        -   ReadWriteOnce
    hostPath:
        path: "/mnt/data"

  